### ISSUE TITLE
please have a look at ansigenome for some inspitatiopn

### ISSUE THREAD

**Issue by mihai-satmarean** [murphypetercl/ansible-mdgen#20]
Hi, great initiative and great timing,
I was the other day speaking with someone from the Ansible dev team about the necessity to have role documentation automated.
Years ago we were using ansigenome, it implements a nice templating feature too.
I will forward your work to the ansible team, hopefully, finally we can have documentation.
For us is important that documentation gets generated on a pre-commit hook, by using a docker container....
Cheers,
Mihai

**Comment by murphypetercl** [comment]
Hi Mahai, thanks, I appreciate the feedback. Would be great to hear what the ansible team think.

I will take a look at the ansigenome project. If you have any feature ideas you'd like to see added, please let me know or if you'd like to contribute, very welcome.

Thanks
Peter
