### ISSUE TITLE
@var does not render Umlauts

### ISSUE THREAD

**Issue by madic-creates** [murphypetercl/ansible-mdgen#24]
German Umlauts, ä ö ü, aren't rendered correctly. They get replaced.

Example:
```
#  @var: MONITORING: für
```

The ü is rendered as **\xFC**

**Comment by murphypetercl** [comment]
Hi Madic - I have put in a fix for this issue. Please download the latest version and retry, thanks.

**Comment by madic-creates** [comment]
Thank you!
